BG_COLOR = "#F7F8FA"
THEME = {
    "#F0F7FF": "#3B82F6",  # Голубой
    "#E2E8F0": "#334155",  # Светло-серый
    "#E0F2F1": "#009688",  # Бирюзовый
}
LANGUAGES = {
    "Russian": {
        "main_title": "ПАЛОЧКИ",
        "play": "Новая игра",
        "settings": "Настройки",
        "exit": "Выход",
        "back": "← Назад",
        "next": "Далее →",
        "start_game": "Начать игру",
        "mode_title": "Выберите режим игры",
        "vs_bot": "Игра с ботом",
        "vs_friend": "Игра с другом",
        "diff_title": "Выберите уровень сложности",
        "easy": "Простой",
        "medium": "Средний",
        "hard": "Сложный",
        "about": "Об игре",
        "size_title": "Выберите размер игрового поля",
        "4x4": "4x4",
        "6x6": "6x6",
        "8x8": "8x8",
        "confirm_exit": "Вы уверены, что хотите выйти?",
        "cancel": "Отмена",
        "confirm": "Подтвердить",
        "lang_label": "Язык",
        "theme_label": "Цветовая тема",
        "new_game": "↻ Новая игра",
        "main_menu": "⌂ Главное Меню",
        "turn_p1": "Ход игрока 1",
        "turn_p2": "Ход игрока 2",
        "turn_bot": "Ход бота",
        "player1": "Игрок 1",
        "player2": "Игрок 2",
        "bot": "Бот",
        "wins": "Победил!",
        "draw": "Ничья!",
        "result_title": "Результаты игры",
        "desc": "«Палочки» - это стратегическая игра. Игроки по очереди соединяют точки. Как только вы запустите игру, перед вами появится поле из точек. Нажимая между точками вы ставите линию. Чтобы присвоить квадрат себе, нужно заключить его линиями своего цвета. Завершив квадрат, вы получаете очко и дополнительный ход. Выиграет тот, кто закрасит больше квадратов. Удачи!"
    },
    "English": {
        "main_title": "STICKS",
        "play": "New Game",
        "settings": "Settings",
        "exit": "Exit",
        "back": "← Back",
        "next": "Next →",
        "start_game": "Start Game",
        "mode_title": "Select Game Mode",
        "vs_bot": "vs Bot",
        "vs_friend": "vs Friend",
        "diff_title": "Select difficulty level",
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "about": "About",
        "size_title": "Select Grid Size",
        "4x4": "4x4",
        "6x6": "6x6",
        "8x8": "8x8",
        "confirm_exit": "Are you sure you want to exit?",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "lang_label": "Language",
        "theme_label": "Сolor theme",
        "new_game": "↻ New Game",
        "main_menu": "⌂ Menu",
        "turn_p1": "Player 1 Turn",
        "turn_p2": "Player 2 Turn",
        "turn_bot": "Bot Turn",
        "player1": "Player 1",
        "player2": "Player 2",
        "bot": "Bot",
        "wins": "Wins!",
        "draw": "Draw!",
        "result_title": "Game Results",
        "desc": "«Sticks» is a strategy game. Players take turns connecting dots. Once you start the game, a grid of dots appears. By clicking between the dots, you draw a line. To claim a square, you must enclose it with lines of your color. Completing a square earns you a point and an extra turn. The player who fills the most squares wins. Good luck!"
    }
}